// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheWindCorner.Data;

#nullable disable

namespace TheWindCorner.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415201440_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("BlogPost Identifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the admin who created the blog-post");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time when the blog-post was added");

                    b.Property<string>("FullText")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The full text of the blog-post");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("If the blog-post has been deleted");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasComment("A summery of the blog-post");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComment("A short descriptive title for the blog-post");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("BlogPosts", t =>
                        {
                            t.HasComment("A blog-post posted by the admin");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Comments.EventComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the comment made");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the user, who made the comment");

                    b.Property<DateTime>("CommentedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time the comment was added");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The full text of the comment");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the event, that was commented");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("If the comment has been deleted");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit")
                        .HasComment("If the comment has been edited");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EventId");

                    b.ToTable("EventComments", t =>
                        {
                            t.HasComment("The comment on an event");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Comments.ItemComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the comment made");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the user, who made the comment");

                    b.Property<DateTime>("CommentedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time the comment was added");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The full text of the comment");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("If the comment has been deleted");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit")
                        .HasComment("If the comment has been edited");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the item, that was commented");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemComments", t =>
                        {
                            t.HasComment("The comment on an item");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Comments.SpotComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the comment made");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the user, who made the comment");

                    b.Property<DateTime>("CommentedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time the comment was added");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The full text of the comment");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("If the comment has been deleted");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit")
                        .HasComment("If the comment has been edited");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the spot, that was commented");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SpotId");

                    b.ToTable("SpotComments", t =>
                        {
                            t.HasComment("The comment on a spot");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Comments.WantedItemComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the comment made");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the user, who made the comment");

                    b.Property<DateTime>("CommentedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time the comment was added");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The full text of the comment");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("If the comment has been deleted");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit")
                        .HasComment("If the comment has been edited");

                    b.Property<Guid>("WantedItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the wanted item, that was commented");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("WantedItemId");

                    b.ToTable("WantedItemComments", t =>
                        {
                            t.HasComment("The comment on a wanted item");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Event Identifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the admin who created the event");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time when the event was created");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time, when the event ends");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("A full description of the event");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("If the event has been deleted");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("The location, where the event is to be held");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasComment("A short description of the event");

                    b.Property<Guid?>("SpotId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The Identifier of the spot, where the event takes place");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time, when the event starts");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The status of the event");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComment("A short descriptive title for the event");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SpotId");

                    b.ToTable("Events", t =>
                        {
                            t.HasComment("A wind-sports event posted by the admin");

                            t.HasCheckConstraint("CK_Events_End_After_Start", "[End] > [Start]");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Image Identifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasComment("The display order of the image, 0 being the main image");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the entity this image belongs to");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("The type of entity this image belongs to");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("The path or URL of the image");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "DisplayOrder");

                    b.ToTable("Images", t =>
                        {
                            t.HasComment("Image associated with a listed entity");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Item Identifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The Brand Name of the Item");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The Category of the Item");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The Identifier of the user who added the item listing");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time, when the item was listed for sale");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("A full description of the item");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("If the Item has been approved for listing");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("If the Item has been deleted");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit")
                        .HasComment("If the Item has been sold");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The Type of the Item");

                    b.Property<string>("Model")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("The Model Name of the Item");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The Price of the Item");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("The Size of the Item");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComment("A short descriptive title for the item");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasComment("The Year of the Item's production or collection");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Items", t =>
                        {
                            t.HasComment("Item listed for sale");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the notification");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The type of the notification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time the notification was sent");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the entity that triggered the notification");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The type of the entity");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit")
                        .HasComment("If the notified action has been handled by the admin");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasComment("If the notification has been read by the admin");

                    b.Property<Guid>("TriggeredById")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the user whose action triggered the notification");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredById");

                    b.HasIndex("IsRead", "IsHandled");

                    b.ToTable("Notifications", t =>
                        {
                            t.HasComment("Notification to the admin about user's action");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Spot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the spot");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the user, who added this spot");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time, when the spot was added");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("A full description of the spot");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("If the spot has been approved for listing");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("If the spot has been deleted");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasComment("The latitude of the spot's location");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasComment("The longitude of the spot's location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The name of the spot");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Spots", t =>
                        {
                            t.HasComment("A location, where one of the wind-sports can be practiced");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.WantedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The identifier of the wanted item");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The Category of the Item");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The Identifier of the user who added the listing of the item they are seeking");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time, when the sought item was listed");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("A full description of the wanted item");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("If the wanted item has been approved for listing");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("If the wanted item has been deleted");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("bit")
                        .HasComment("If the wanted item has been bought");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComment("A short descriptive title for the wanted item");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("WantedItems", t =>
                        {
                            t.HasComment("Item that an user is looking for");
                        });
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.User.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time when the user has been created");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time when the user has been deleted");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The first name of the user");

                    b.Property<Guid?>("HomeSpotId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The Identifier of the home spot of the user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("If the user has been deleted");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The last name of the user");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time when the user has been modified");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The path or URL of the user's profile image");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("HomeSpotId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.BlogPost", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", "CreatedBy")
                        .WithMany("BlogPosts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Comments.EventComment", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TheWindCorner.Data.Models.Entities.Event", "Event")
                        .WithMany("Comments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Comments.ItemComment", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TheWindCorner.Data.Models.Entities.Item", "Item")
                        .WithMany("Comments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Comments.SpotComment", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TheWindCorner.Data.Models.Entities.Spot", "Spot")
                        .WithMany("Comments")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Comments.WantedItemComment", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TheWindCorner.Data.Models.Entities.WantedItem", "WantedItem")
                        .WithMany("Comments")
                        .HasForeignKey("WantedItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("WantedItem");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Event", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", "CreatedBy")
                        .WithMany("Events")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TheWindCorner.Data.Models.Entities.Spot", "Spot")
                        .WithMany("Events")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Item", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", "CreatedBy")
                        .WithMany("ItemsForSale")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Notification", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TriggeredBy");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Spot", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", "CreatedBy")
                        .WithMany("AddedSpots")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.WantedItem", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.User.ApplicationUser", "CreatedBy")
                        .WithMany("WantedItems")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.User.ApplicationUser", b =>
                {
                    b.HasOne("TheWindCorner.Data.Models.Entities.Spot", "HomeSpot")
                        .WithMany("HomeSpotUsers")
                        .HasForeignKey("HomeSpotId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HomeSpot");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Event", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Item", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.Spot", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Events");

                    b.Navigation("HomeSpotUsers");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.Entities.WantedItem", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TheWindCorner.Data.Models.User.ApplicationUser", b =>
                {
                    b.Navigation("AddedSpots");

                    b.Navigation("BlogPosts");

                    b.Navigation("Events");

                    b.Navigation("ItemsForSale");

                    b.Navigation("WantedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
